import Head from 'next/head';
import Image from 'next/image';
import Router from 'next/router';
import React, { useContext, useEffect, useState } from 'react';
import { FaCheckDouble, FaChevronLeft, FaChevronRight } from 'react-icons/fa';
import Swal from 'sweetalert2';
import Footer from '../../components/Footer/Footer';
import Navbar from '../../components/Navbar/Navbar';
import { CartContext } from '../../Context/CardContext';
import styles from '../../styles/singleproduct.module.scss';

const productDetail = ({product}) => {
    const [sliderNum, setSliderNum] = useState(0)
    const [quantity, setQuantity] = useState(1)
    const [cartItem, setCartItem] = useState([]);
    const [onCart, setOnCart] = useState(false);

    const {state, dispatch} = useContext(CartContext);
    
    // find the product from localstorage and check if it exists
    useEffect(() => {
        const items = typeof window !== 'undefined' && JSON.parse(localStorage.getItem('productlist'))
        setCartItem(items)
    }, [])

    // check if the product is already in cart
    const isTrueFalse = cartItem.find((pr) => pr._id === product._id)

    // slide between products images
    const lastImg = product.images?.length - 1;
    const handleClick = (e) => {
        let newSliderNum;
        if (e === "inc") {
            newSliderNum = sliderNum === 0 ? lastImg :  sliderNum - 1
        } else {
            newSliderNum = sliderNum === lastImg ? 0 :  sliderNum + 1
        }

        setSliderNum(newSliderNum)
    }

    const Toast = Swal.mixin({
        toast: true,
        position: 'bottom-end',
        showConfirmButton: false,
        width: "15rem",
        timer: 3000,
        timerProgressBar: true,
        didOpen: (toast) => {
          toast.addEventListener('mouseenter', Swal.stopTimer)
          toast.addEventListener('mouseleave', Swal.resumeTimer)
        }
      })

    const addToCart = () => {
        const date = new Date().getMilliseconds()
        console.log(date);
        const mainProduct = {
            ...product,
            id: product._id + '-' + date,
            quantity: quantity,
        }

        try {
            dispatch({type: 'ADD_TO_LIST', payload: mainProduct})

        Toast.fire({
            icon: 'success',
            title: 'Added to Cart',
          })

          Router.push('/cart')
        } catch (error) {
            console.log(error);
        }
        
    }
    
return (
    <div className={styles.product_detail_page}>
    <Head>
          <title>Lucianaschiles - Product</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
            <div className={styles.product_detail_page}>
                <div className={styles.detail_page_left}>
                <div className={styles.detail_page_slider}>
                    <div className={styles.slider_main}>
                        <Image src={product?.images[sliderNum]} width={500} height={500} alt="product img" className={styles.slider_main_imgg} />
                        
                        <div className={styles.slider_btnss}>
                            <FaChevronLeft size={35} className={styles.slide_icon} onClick={() => handleClick("inc")} />
                            <FaChevronRight size={35} className={styles.slide_icon} onClick={() => handleClick("dec")} />
                        </div>
                    </div>

                    <div className={styles.slider_btm_imgs}>
                        {product.images?.map((img, i) => {
                        return <Image key={i} src={img} onClick={() => setSliderNum(i)} alt="product img" className={styles.slider_btm_img} height={50} width={70} />
                        })}
                    </div>
                </div>

                <div className={styles.res_priceee}>
                    <h2 className={styles.product_title}>{product.title}</h2>
                    <h2 className={styles.product_price}>USD {product.price}</h2>
                    <span style={{fontSize: "14px", color: 'rgb(66, 65, 65)'}}>Local taxes included (where applicable)</span>
                    <p style={{color: 'black', marginTop: '40px'}}>Quantity</p>
                    {/* <input type="number" value={quantity} min={1} max={20} onChange={(e) => setQuantity(e.target.value)} className={styles.product_quantity}/> */}
                    <select value={quantity} onChange={(e) => setQuantity(e.target.value)} className={styles.product_quantity2}>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                    </select>
                    
                    <button onClick={addToCart} disabled={isTrueFalse} style={{cursor: isTrueFalse ? 'not-allowed' : 'pointer'}}>{isTrueFalse ? "Added to Cart" : "Add to Cart"}</button>

                    <div className={styles.highlight}>
                        <h3>Highlights</h3>
                        {product.highlights.map((highlight, i) => {
                            return <p key={i}><FaCheckDouble style={{marginRight: '5px'}} size={15} /> {highlight}</p>
                        })}
                    </div>
                </div>

                    {product.detail.map((detail, i) => {
                       return <p key={i} className={styles.detail_secs}>{detail}</p>
                    })}
                </div>

                <div className={styles.detail_page_right}>
                    <h2 className={styles.product_title}>{product.title}</h2>
                    <h2 className={styles.product_price}>USD {product.price}</h2>
                    <span style={{fontSize: "14px", color: 'rgb(66, 65, 65)'}}>Local taxes included (where applicable)</span>
                    <p style={{color: 'black', marginTop: '40px'}}>Quantity</p>
                    
                    {/* <input type="number" value={quantity} min={1} max={20} onChange={(e) => setQuantity(e.target.value)} className={styles.product_quantity}/> */}
                    <select value={quantity} onChange={(e) => setQuantity(e.target.value)} className={styles.product_quantity2}>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                    
                    <button onClick={addToCart} disabled={isTrueFalse} style={{cursor: isTrueFalse ? 'not-allowed' : 'pointer'}}>{isTrueFalse ? "Added to Cart" : "Add to Cart"}</button>

                    <div className={styles.highlight}>
                        <h3>Highlights</h3>
                        {product.highlights.map((highlight, i) => {
                            return <p key={i}><FaCheckDouble style={{marginRight: '5px'}} size={15} /> {highlight}</p>
                        })}
                    </div>
                </div>
            </div>
        <Footer />
    </div>
);
}

export default productDetail;

export async function getStaticPaths() {
    const res = await fetch('https://lucianaschiles-backend.onrender.com/api/products/all')
  
    const data = await res.json();
    const products = data.message;

    const paths = products.map((items) => ({
        params: {
            productid: items._id
        }
    }));
    
    return {
        paths,
        fallback: false,
    }
  }  

export async function getStaticProps(context) {
    const {params} = context;

    const res = await fetch(`https://lucianaschiles-backend.onrender.com/api/products/${params.productid}`)
  
    const data = await res.json();
  
    const product = data.message;
    return {
      props: {
        product: product || null,
      },
    }
}