import Head from 'next/head'
import React from 'react'
import Footer from '../../components/Footer/Footer'
import Navbar from '../../components/Navbar/Navbar'
import Products from '../../components/Products/Products'
import styles from '../../styles/productpage.module.scss'

const index = ({products}) => {
  return (
    <div className={styles.proudct_page}>
      <Head>
          <title>Lucianaschiles - Products</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* <SectionHeader title="ALL PRODUCTS" /> */}
      <Products products={products} title="ALL PRODUCTS" />
      <Footer />
    </div>
  )
}

export default index

export async function getStaticProps() {
  const res = await fetch('https://lucianaschiles-backend.onrender.com/api/products/all')

  const data = await res.json();

  const products = data.message;
  return {
    props: {
      products: products || null,
    },
  }
}  