import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'
import CartsProduct from '../../components/CartsProduct/CartsProduct'
import Footer from '../../components/Footer/Footer'
import Navbar from '../../components/Navbar/Navbar'
import styles from '../../styles/cartpage.module.scss'

const index = () => {
  const [cartItem, setCartItem] = useState([]);
  const [totalPrice, settotalPrice] = useState(0);
  // const [subTotal, setSubTotal] = useState(0);

  const subtotal = cartItem.map((item, i) => {
    let total;
    total = item.price + item.price
    console.log(total);
  })



  useEffect(() => {
    const items = typeof window !== 'undefined' && JSON.parse(localStorage.getItem('productlist'))
    setCartItem(items)
  }, [])

  const handleCheckout = () => {
    console.log(totalPrice);
  }

  return (
    <div className={styles.cart_page}>
    <Head>
          <title>Lucianaschiles - Cart</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
            <div className={styles.cart_page_main}>
              <div className={styles.cart_page_main_cart}>
                  {cartItem.length === 0 ? (<div className={styles.cart_page_empty}>
                      <h3>Your cart is empty.</h3>
                      <p>Find Products <Link href="/products" style={{textDecoration: 'underline'}}>Here.</Link></p>
                  </div>) : cartItem.map((item) => {
                    return (
                      <>
                        <CartsProduct key={item._id} item={item} />
                        <hr />
                      </>
                    )
                  })}
              </div>

              {cartItem.length !== 0 && <div className={styles.cart_page_checkout}>
                  <h2>Order Info</h2>
                  <div className={styles.checkout_detail}>
                    <p>Total item </p>
                    <p>{cartItem.length}</p>
                  </div>
                  <div className={styles.checkout_detail}>
                    <p>Subtotal </p>
                    <p>USD {subtotal}</p>
                  </div>
                  <div className={styles.checkout_detail}>
                    <p>Shipping Price </p>
                    <p>USD 55</p>
                  </div>
                  <hr />
                  <div className={styles.checkout_detail}>
                    <p>Total Price </p>
                    <span>USD {505}</span>
                  </div>

                  <button type='button' onClick={handleCheckout}>Checkout USD 99</button>
              </div>}
            </div>
        <Footer />
    </div>
  )
}

export default index