import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import CartsProduct from '../../components/CartsProduct/CartsProduct'
import Footer from '../../components/Footer/Footer'
import Navbar from '../../components/Navbar/Navbar'
import styles from '../../styles/cartpage.module.scss'

const index = () => {
  const [cartItem, setCartItem] = useState([]);
  const [totalPrice, settotalPrice] = useState(0);
  const [subTotal, setSubTotal] = useState(0);
  const location = useRouter()
  
  // get all the products from the localstorage
  useEffect(() => {
    const fetchData = async () => {
      const items = await typeof window !== 'undefined' && JSON.parse(localStorage.getItem('productlist'))
      setCartItem(items)
      }
      fetchData()

      const stotal = cartItem?.map((item, i) => {

        return item[i].price * item[i].quantity
        
      })

      console.log(stotal);
  }, [])
  
  // the function checks the duplicates items. But no need ot use it for now. I have checked if the product already exists or not, on the product detail page.
  
  // const filteredProduct = cartItem.filter((value, index) => { 
  //   return cartItem.indexOf(value) === index;
  // });

  // Need to update
  const handleCheckout = () => {
    // console.log(totalPrice);
  }

  return (
    <div className={styles.cart_page}>
    <Head>
          <title>Lucianaschiles - Cart</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
            <div className={styles.cart_page_main}>
              <div className={styles.cart_page_main_cart}>
                  {cartItem.length === 0 ? ( <div className={styles.cart_page_empty}>
                      <h3>Your cart is empty.</h3>
                      <p>Find Products <Link href="/products" style={{textDecoration: 'underline'}}>Here.</Link></p>
                  </div>) : cartItem.map((item) => {
                    return (
                      <>
                        <CartsProduct key={item._id} item={item} />
                        <hr />
                      </>
                    )
                  })}
              </div>

              {cartItem.length !== 0 && <div className={styles.cart_page_checkout}>
                  <h2>Order Info</h2>
                  <div className={styles.checkout_detail}>
                    <p>Total item </p>
                    <p>{cartItem.length}</p>
                  </div>
                  <div className={styles.checkout_detail}>
                    <p>Subtotal </p>
                    <p>USD {subTotal}</p>
                  </div>
                  <div className={styles.checkout_detail}>
                    <p>Shipping Price </p>
                    <p>USD 55</p>
                  </div>
                  <hr />
                  <div className={styles.checkout_detail}>
                    <p>Total Price </p>
                    <span>USD {505}</span>
                  </div>

                  <button type='button' onClick={handleCheckout}>Checkout USD 99</button>
              </div>}
            </div>
        <Footer />
    </div>
  )
}

export default index