import Head from 'next/head'
import React from 'react'
import Footer from '../../components/Footer/Footer'
import Navbar from '../../components/Navbar/Navbar'
import styles from '../../styles/aboutuspage.module.scss'

const index = () => {
  return (
    <div className={styles.aboutus_page}>
    <Head>
          <title>Lucianaschiles - About</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
            <div className={styles.aboutus_page_main}>
                <h2>About us page(updating)</h2>
            </div>
        <Footer />
    </div>
  )
}

export default index